CREATE TABLE IF NOT EXISTS PRIVATE_MESSAGE
(
    user_id   INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    date      DATE,
    text      VARCHAR(2000),
    FOREIGN KEY (user_id) REFERENCES USER_SOCIAL_NETWORK (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES USER_SOCIAL_NETWORK (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);