CREATE TABLE IF NOT EXISTS FRIENDS_USER
(
    user_id   INTEGER,
    friend_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES USER_SOCIAL_NETWORK (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES USER_SOCIAL_NETWORK (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id),
    CHECK (FRIENDS_USER.friend_id != FRIENDS_USER.user_id)
);