INSERT INTO SCHOOL VALUES (1, 'School №5');
INSERT INTO SCHOOL VALUES (2, 'School №24');
INSERT INTO SCHOOL VALUES (3, 'School №42');
INSERT INTO SCHOOL VALUES (4, 'School №65');
INSERT INTO SCHOOL VALUES (5, 'School №30');
INSERT INTO SCHOOL VALUES (6, 'School №3');
INSERT INTO SCHOOL VALUES (7, 'School №85');